import { Book, Category } from './types';

export const categories: Category[] = [
  { id: '1', name: 'novels', nameAr: 'روايات', icon: '📚', bookCount: 45 },
  { id: '2', name: 'religion', nameAr: 'دين', icon: '🕌', bookCount: 32 },
  { id: '3', name: 'science', nameAr: 'علوم', icon: '🔬', bookCount: 28 },
  { id: '4', name: 'history', nameAr: 'تاريخ', icon: '📜', bookCount: 35 },
  { id: '5', name: 'psychology', nameAr: 'علم النفس', icon: '🧠', bookCount: 22 },
  { id: '6', name: 'philosophy', nameAr: 'فلسفة', icon: '💭', bookCount: 18 },
  { id: '7', name: 'kids', nameAr: 'كتب أطفال', icon: '🧒', bookCount: 40 },
  { id: '8', name: 'school', nameAr: 'كتب مدرسية', icon: '🎓', bookCount: 55 },
  { id: '9', name: 'poetry', nameAr: 'شعر', icon: '✨', bookCount: 25 },
  { id: '10', name: 'self-help', nameAr: 'تطوير الذات', icon: '🌱', bookCount: 30 },
];

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'رحلة ابن بطوطة',
    author: 'ابن بطوطة',
    description: 'كتاب يروي رحلات ابن بطوطة حول العالم الإسلامي والعالم القديم، من أشهر كتب الرحلات في التاريخ العربي والإسلامي.',
    category: 'history',
    coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop',
    pdfUrl: '/sample.pdf',
    createdAt: '2024-01-15',
    featured: true,
  },
  {
    id: '2',
    title: 'مقدمة ابن خلدون',
    author: 'ابن خلدون',
    description: 'المقدمة الشهيرة التي وضعها ابن خلدون لكتابه العبر، تعتبر من أهم الكتب في علم الاجتماع والتاريخ.',
    category: 'philosophy',
    coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop',
    pdfUrl: '/sample.pdf',
    createdAt: '2024-01-10',
    featured: true,
  },
  {
    id: '3',
    title: 'ألف ليلة وليلة',
    author: 'مؤلف مجهول',
    description: 'مجموعة قصص شعبية من التراث العربي والفارسي والهندي، تحكي حكايات شهرزاد.',
    category: 'novels',
    coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop',
    pdfUrl: '/sample.pdf',
    createdAt: '2024-01-08',
    featured: true,
  },
  {
    id: '4',
    title: 'الأمير الصغير',
    author: 'أنطوان دو سانت إكزوبيري',
    description: 'قصة فلسفية رائعة عن طيار يلتقي بأمير صغير من كوكب آخر.',
    category: 'novels',
    coverUrl: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=400&fit=crop',
    pdfUrl: '/sample.pdf',
    createdAt: '2024-01-05',
  },
  {
    id: '5',
    title: 'العقل الباطن',
    author: 'جوزيف ميرفي',
    description: 'كتاب يتحدث عن قوة العقل الباطن وكيفية استخدامها لتحقيق النجاح.',
    category: 'psychology',
    coverUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=300&h=400&fit=crop',
    pdfUrl: '/sample.pdf',
    createdAt: '2024-01-03',
  },
  {
    id: '6',
    title: 'رياض الصالحين',
    author: 'الإمام النووي',
    description: 'كتاب جامع للأحاديث النبوية الشريفة مرتب على أبواب الفقه والأخلاق.',
    category: 'religion',
    coverUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=300&h=400&fit=crop',
    pdfUrl: '/sample.pdf',
    createdAt: '2024-01-01',
  },
  {
    id: '7',
    title: 'قصص الأنبياء',
    author: 'ابن كثير',
    description: 'كتاب يروي قصص الأنبياء والرسل من آدم إلى محمد صلى الله عليه وسلم.',
    category: 'religion',
    coverUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=300&h=400&fit=crop',
    pdfUrl: '/sample.pdf',
    createdAt: '2023-12-28',
    featured: true,
  },
  {
    id: '8',
    title: 'الكون في قشرة جوز',
    author: 'ستيفن هوكينج',
    description: 'كتاب علمي مبسط عن الفيزياء النظرية والكون.',
    category: 'science',
    coverUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=300&h=400&fit=crop',
    pdfUrl: '/sample.pdf',
    createdAt: '2023-12-25',
  },
];
